module.exports = {
    TBL_CONTACTS_MASTER: 'ezb_wa_contacts',
    TBL_SYSTEM_CONFIG_MASTER: 'ezb_system_config',
    TBL_TEMPLATE_MASTER: 'ezb_wa_templates',
    TBL_MEDIA_MASTER: 'ezb_wa_media',
    TBL_REQUEST_MASTER: 'ezb_message_request_master',
    TBL_MESSAGE_REQUEST_MASTER: 'ezb_message_request_master',
    TBL_MESSAGE_SENT_MASTER: 'ezb_message_sent_master',
    TBL_API_KEYS_MASTER: 'ezb_wa_api_keys',
    TBL_USERS_MASTER: 'ezb_users',
    TBL_TEMPLATE_MASTER: 'ezb_wa_templates',
    TBL_WA_MSG_SETTINGS_MASTER: 'ezb_wa_msg_settings',
    TBL_WA_MEDIA_MASTER: 'ezb_wa_media',
    TBL_SYSTEM_CONFIG_MASTER: 'ezb_system_config',
    TBL_CAMPAIGN_MASTER: 'ezb_wa_campaign_master',
    TBL_SUBSCRIPTION_MASTER: 'ezb_subscription_master',
    TBL_EZB_CATLOUGE_MASTER: 'ezb_catlogue_master',
    TBL_WA_TEMPLATE_CATALOG_DETAILS: 'ezb_wa_template_catalog_details',
};